<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require ( get_template_directory() . '/includes/functions.php' );
require ( get_template_directory() . '/includes/theme-options.php' );
require ( get_template_directory() . '/includes/post-custom-meta.php' );
require ( get_template_directory() . '/includes/tha-theme-hooks.php' );
require ( get_template_directory() . '/includes/hooks.php' );
require ( get_template_directory() . '/includes/version.php' );


//CPT UI
add_action('init', 'cptui_register_my_cpt_urteil');
function cptui_register_my_cpt_urteil() {
register_post_type('urteil', array(
'label' => 'Urteil',
'description' => 'Urteil',
'public' => true,
'show_ui' => true,
'show_in_menu' => true,
'capability_type' => 'post',
'map_meta_cap' => true,
'hierarchical' => false,
'rewrite' => array('slug' => 'urteil', 'with_front' => true),
'query_var' => true,
'supports' => array('title','editor','excerpt','trackbacks','custom-fields','comments','revisions','thumbnail','author','page-attributes','post-formats'),
'labels' => array (
  'name' => 'Urteil',
  'singular_name' => 'Urteil',
  'menu_name' => 'Urteil',
  'add_new' => 'Add Urteil',
  'add_new_item' => 'Add New Urteil',
  'edit' => 'Edit',
  'edit_item' => 'Edit Urteil',
  'new_item' => 'New Urteil',
  'view' => 'View Urteil',
  'view_item' => 'urteil',
  'search_items' => 'Search Urteil',
  'not_found' => 'No Urteil Found',
  'not_found_in_trash' => 'No Urteil Found in Trash',
  'parent' => 'Parent Urteil',
)
) ); }


//jQuery
/* jQuery von WordPress deaktivieren und über Google laden */
function my_scripts_method() {
    wp_deregister_script( 'jquery' );
    wp_register_script( 'jquery', 'http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js'); // hier kann auch eine andere Quelle angegeben werden, z.B. jQuery oder Microsoft. Siehe: http://jquery.com/download/ 
    wp_enqueue_script( 'jquery' );
}  
add_action('wp_enqueue_scripts', 'my_scripts_method');


